Use replicas field when scheduling pods
stackabletech/operator-rs pull request #166
Opened 2021-07-12 10:01 UTC by maltesander

The replicas field in the role group now is taken into account when scheduling pods or deleting excess pods. 
For now it is simply based on a random number (which nodes are selected if multiple match or which pods are taken of nodes if excess).

2021-07-12 14:08 UTC, lfrancke requested changes
Somehow I can't believe that this is it.....my only comments are about documentation I believe.

I have a nagging feeling that we're missing something though.

2021-07-12 14:08 UTC, lfrancke commented on src/role_utils.rs
> +/// Return a list of eligible nodes and the provided replicas count for each role and group
Also: This could now benefit from a proper comment which explains the input type.

2021-07-13 07:58 UTC, maltesander commented on src/k8s_utils.rs
> +    let nodes_that_need_pods = candidate_nodes
But that is still true for one role group? I updated the comment with a hint on that.

2021-07-16 10:10 UTC, lfrancke submitted a review, later dismissed
Minor comment things

2021-07-16 10:10 UTC, lfrancke commented on src/k8s_utils.rs
> +/// a random subset representing the size difference of "replicas" and "nodes_that_need_pods" is selected.
```suggestion
/// a random subset representing the size difference between "replicas" and "nodes_that_need_pods" is selected.
```

2021-07-23 08:39 UTC, soenkeliebau approved these changes
As Lars is on vacation I've gone over his comments and that all looks good to me.

2021-07-23 09:58 UTC, merged