[Merged by Bors] - Add support for logging to Jaeger
stackabletech/operator-rs pull request #360
Opened 2022-03-21 14:40 UTC by teozkr

## Description

This enables individual operators to export logs to Jaeger. However, operator packaging must also be modified to add a `jaeger-agent` sidecar and enable tracing where applicable.

Logging to Jaeger is opt-in, since otherwise it clogs up the local logs with errors about failing to submit traces.

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2022-03-28 14:34 UTC, maltesander requested changes
LGTM, just one thing. I fixed the doc errors and would mark this as breaking?

2022-03-28 14:34 UTC, maltesander commented on CHANGELOG.md
> +- `initialize_logging` now takes an app name and tracing target ([#360]).
This is breaking?

2022-03-30 12:08 UTC, soenkeliebau reviewed
Looks good to me overall, I haven't tested it though, because I am not familiar with Jaeger at all and it would probably have taken me very long to get a test setup going..

2022-03-30 12:09 UTC, teozkr commented on CHANGELOG.md
> +- `initialize_logging` now takes an app name and tracing target ([#360]).
Absolutely, yeah..

2022-04-05 12:09 UTC, maltesander approved these changes
LGTM.

2022-04-07 07:07 UTC, teozkr commented
bors r+

2022-04-07 07:16 UTC, closed without merging