Add AuthenticationClass::resolve
stackabletech/operator-rs pull request #432
Opened 2022-07-05 12:55 UTC by sbernauer

## Description

*Please add a description here. This will become the commit message of the merge request later.*

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2022-07-05 14:19 UTC, maltesander requested changes
One minor thing. LGTM otherwise.

2022-07-05 14:19 UTC, maltesander commented on CHANGELOG.md
> +[#432]: https://github.com/stackabletech/operator-rs/pull/408
```suggestion
[#432]: https://github.com/stackabletech/operator-rs/pull/432
```

2022-07-06 07:11 UTC, maltesander approved these changes
LGTM.

2022-07-06 07:11 UTC, sbernauer commented
thx!

2022-07-06 07:15 UTC, closed without merging