feat: Add support for webhook servers
stackabletech/operator-rs pull request #730
Opened 2024-01-26 10:22 UTC by Techassi

Supersedes #695

This adds support to create webhook servers based on `axum`. The crate _can_ provide multiple pre-configured servers, for example to handle CRD conversion requests.

2024-02-13 09:48 UTC, Techassi commented
The crates are now all up-to-date. This PR is now reviewable.

2024-02-13 13:38 UTC, NickLarsenNZ requested changes
I generally approve, but left enough comments that I assume changes will be made.

2024-02-13 13:46 UTC, Techassi commented on stackable-webhook/src/lib.rs
> +}
Yes, we could make it private. For now, there is no need to export it.

2024-02-13 13:52 UTC, Techassi commented on stackable-webhook/src/lib.rs
> +/// This trait is usually not implemented by external callers and this library
Same as above.

2024-02-13 13:56 UTC, Techassi commented on stackable-webhook/src/lib.rs
> +            }
I would be happy to remove it entirely, but let's see if other reviewers have different opinions.

2024-02-13 14:20 UTC, Techassi commented on stackable-webhook/src/options.rs
> +    pub fn socket_addr(mut self, socket_ip: impl Into<IpAddr>, socket_port: u16) -> Self {
Sure!

2024-02-13 14:23 UTC, soenkeliebau commented on stackable-webhook/src/lib.rs
> +        info!("running TLS server");
I think its a fairly common frame of mind regarding loglevels, yeah.

2024-02-13 14:29 UTC, Techassi commented on stackable-webhook/src/servers/conversion.rs
> +            Json(review)
Nice idea, gonna add it as a middleware to the core router.

2024-02-13 14:33 UTC, Techassi commented on stackable-webhook/src/tls/certs.rs
> +        pk_encoding: PrivateKeyEncoding,
Will update it accordingly.

2024-02-13 14:53 UTC, Techassi commented on stackable-webhook/src/lib.rs
> +}
Changed in d0ea673

2024-02-13 14:53 UTC, Techassi commented on stackable-webhook/src/lib.rs
> +/// This trait is usually not implemented by external callers and this library
Changed in d0ea673

2024-02-13 14:54 UTC, Techassi commented on stackable-webhook/src/tls/certs.rs
> +        pk_encoding: PrivateKeyEncoding,
Changed in 2e53410

2024-02-13 15:03 UTC, Techassi commented on stackable-webhook/src/lib.rs
> +        info!("running TLS server");
Alright, I will change `info!()` to `debug!()`.

2024-02-13 15:26 UTC, NickLarsenNZ commented on stackable-webhook/src/lib.rs
> +/// /// implementation is part of the [`ConversionWebhookServer`].
Duplicate doc-comment thing

```suggestion
/// implementation is part of the [`ConversionWebhookServer`].
```

2024-02-13 15:26 UTC, NickLarsenNZ commented on stackable-webhook/src/servers/conversion.rs
> +            Json(review)
I assume in a separate PR (not necessary to get this feature in).

2024-02-14 12:02 UTC, Techassi commented on stackable-webhook/src/servers/conversion.rs
> +            Json(review)
I added basic high-level request tracing support in e1f538b. I will add full OpenTelemetry compatible tracing in a follow-up PR.

2024-02-14 12:05 UTC, NickLarsenNZ submitted a review, later dismissed
LGTM

2024-02-14 12:05 UTC, NickLarsenNZ commented on stackable-webhook/src/lib.rs
> +        debug!("create core couter and merge provided router");
nit: typo

```suggestion
        debug!("create core counter and merge provided router");
```

2024-02-14 12:14 UTC, Techassi commented on stackable-webhook/src/lib.rs
> +        debug!("create core couter and merge provided router");
Actually, `router` :)

2024-02-14 12:15 UTC, Techassi commented on stackable-webhook/src/lib.rs
> +        debug!("create core couter and merge provided router");
Fixed in e9ffe0e

2024-02-14 12:16 UTC, Techassi commented on stackable-webhook/src/lib.rs
> +            }
Removed in dbc9dd3

2024-02-14 12:16 UTC, Techassi commented on stackable-webhook/src/redirect.rs
Removed in dbc9dd3

2024-02-14 12:16 UTC, Techassi commented on stackable-webhook/src/lib.rs
> +                warn!("webhook runs without automatic HTTP to HTTPS redirect which is not recommended");
Removed in dbc9dd3

2024-02-14 12:16 UTC, Techassi commented on stackable-webhook/src/options.rs
> +/// - The socket binds to 127.0.0.1 on port 8443 (HTTPS)
Removed in dbc9dd3

2024-02-14 12:21 UTC, NickLarsenNZ approved these changes
Lessgooo

2024-02-14 12:26 UTC, merged