refactor: Replace lazy_static with std::sync::LazyLock
stackabletech/operator-rs pull request #827
Opened 2024-07-25 14:05 UTC by Techassi

std::cell::LazyCell and std::sync::LazyLock were stabilized in Rust 1.80.0. We can now use the standard library types instead of the lazy_static crate.

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

2024-07-30 15:18 UTC, NickLarsenNZ requested changes
Just the PR number needs fixing

2024-07-30 15:18 UTC, NickLarsenNZ commented on crates/k8s-version/CHANGELOG.md
> +[#xxx](https://github.com/stackabletech/operator-rs/pull/xxx)
```suggestion
- Replace `lazy_static` with `std::cell::LazyCell` ([#827]).

[#827](https://github.com/stackabletech/operator-rs/pull/827)
```

2024-07-30 15:18 UTC, NickLarsenNZ commented on crates/stackable-operator/src/kvp/key.rs
> +        .expect("failed to compile key prefix regex")
praise: Much appreciated (`unwrap()` -> `expect()`)!

2024-07-31 08:06 UTC, Techassi commented on crates/stackable-operator/src/kvp/key.rs
> +        .expect("failed to compile key prefix regex")
:raised_hands:

2024-07-31 08:09 UTC, NickLarsenNZ approved these changes
LGTM

2024-07-31 08:20 UTC, sbernauer approved these changes

2024-07-31 08:28 UTC, merged