Feat/pub const file header footer
stackabletech/operator-rs pull request #843
Opened 2024-08-21 11:50 UTC by Maleware

# Description

Introducing
```
pub const FILE_HEADER_KEY
pub const FILE_FOOTER_KEY
```

To be used in Superset and Airflow to have unified key names.

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

2024-08-21 13:51 UTC, sbernauer approved these changes
Thanks! Field names match https://github.com/stackabletech/decisions/issues/21

2024-08-21 13:51 UTC, sbernauer requested changes
Can you please add a changelog entry?

2024-08-21 13:52 UTC, sbernauer commented
Can you please also rename the PR to something like `feat: Add constants for configOverrides file header and footer keys`

2024-08-22 07:02 UTC, Maleware commented
Changelog: https://github.com/stackabletech/operator-rs/pull/843/commits/612fbb48a5a05e7987ecd36e72fbd0f244c9242d

Changed name.

2024-08-22 07:06 UTC, sbernauer approved these changes

2024-08-22 07:39 UTC, merged