chore: Dependecy updates, such as kube 0.95.0 and Kubernetes 0.31
stackabletech/operator-rs pull request #867
Opened 2024-09-18 14:27 UTC by sbernauer

# Description

I was **not** able to update opentelemetry, and would let it to the experts to figure it out, CC @Techassi, @NickLarsenNZ and @nightkr 

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

2024-09-18 19:33 UTC, Techassi commented
> I hope the `aws-lc-rs` crate will not cause any problems with Nix. I bumped zookeeper-operator and `make run-dev` worked fine.

We could evaluate if we can use `ring` as a crypt backend instead (supported by rustls).

2024-09-19 06:10 UTC, sbernauer commented
> We could evaluate if we can use ring as a crypt backend instead (supported by rustls).

I sadly know the situation from trino-lb :/ This PR should not change anything (in comparison to main), and the zookeeper test worked, so I'd call it ready to be merged

2024-09-19 06:32 UTC, NickLarsenNZ approved these changes
LGTM

2024-09-19 07:23 UTC, Techassi requested changes
LGTM, two small comments.

2024-09-19 07:23 UTC, Techassi commented on crates/stackable-operator/CHANGELOG.md
> +- Bump to `kube` 0.95.0 and Kubernetes 1.31 ([#867]).
suggestion: This PR not only bumps `kube`, but other dependencies as well.

```suggestion
- Bump Rust dependencies and enable Kubernetes 1.31 (via `kube` 0.95.0) ([#867]).
```

2024-09-19 07:23 UTC, Techassi commented on crates/stackable-operator/src/builder/pod/mod.rs
> +            .extend(secrets.map(|s| LocalObjectReference { name: s }));
nit:

```suggestion
            .extend(secrets.map(|name| LocalObjectReference { name }));
```

2024-09-19 07:26 UTC, Techassi approved these changes

2024-09-19 07:36 UTC, merged